export const CONFIG = {
  world: {
    tileSize: 32,
    roomWidth: 40,
    roomHeight: 30,
    viewWidth: 1280,
    viewHeight: 720,
  },

  player: {
    radius: 10,
    collisionMargin: 0.5,
    speed: 145,
    sprintSpeed: 225,
    stamina: {
      max: 100,
      drainRate: 26,
      rechargeRate: 30,
      rechargeDelay: 0.7,
      restartThreshold: 10,
      lowPercent: 0.25,
      criticalPercent: 0.1,
    },
    acceleration: 1300,
    friction: 920,
    rotationSpeed: 16,
  },

  lighting: {
    // Scales darkness cutout via applyDarkness formula (not direct destination-out alpha)
    ambientStrength: 0.09,
    ambientPlayerRadius: 66,
    // Warm floor spill drawn under the darkness overlay
    ambientFloorSpill: 0.09,
    darknessOpacity: 0.96,
    darknessColor: '3, 5, 8',
    deepShadowOpacity: 0.985,
    mobileBrightnessBoost: 1.02,
  },

  flashlight: {
    range: 400,
    broadRange: 500,
    spillRange: 600,
    fov: Math.PI / 2.2,
    broadFov: Math.PI / 1.55,
    spillFov: Math.PI / 1.25,
    focusedFov: Math.PI / 5,
    intensity: 1,
    power: {
      max: 100,
      drainRate: 9,
      rechargeRate: 6.5,
      rechargeDelay: 1.5,
      restartThreshold: 5,
      lowPercent: 0.3,
      warningPercent: 0.15,
      criticalPercent: 0.05,
    },
    flickerAmount: 0.04,
    angleSmoothing: 16,
    innerAngle: Math.PI / 5,
    warmColor: '#FFF4D6',
    warmCore: '#FFFBE8',
    bloomStrength: 0.58,
  },

  objective: {
    fusePickupExtra: 55,
    generatorPickupExtra: 60,
  },

  enemy: {
    radius: 14,
    walkSpeed: 45,
    chaseSpeed: 85,
    huntSpeed: 70,
    detectionTime: 0.8,
    alertTime: 0.5,
    searchTime: 6,
    lostTime: 3,
    attackRange: 18,
    attackTime: 0.3,
    closeProximityRange: 58,
    awarenessDecay: 0.38,
    memoryTime: 1.5,
    archetypes: {
      STALKER: {
        radius: 14,
        proximityRange: 96,
        losRange: 210,
        sprintRange: 260,
        awarenessGain: 0.75,
        losGain: 0.68,
        sprintGain: 0.75,
        illuminationGain: 2.1,
        awarenessThreshold: 0.34,
        detectionTime: 0.55,
        alertTime: 0.45,
        chaseSpeed: 76,
        huntSpeed: 62,
        searchTime: 8.5,
        lostTime: 4.2,
        searchRadius: 76,
        attackRange: 19,
        stationary: false,
      },
      RUNNER: {
        radius: 12,
        proximityRange: 68,
        losRange: 150,
        sprintRange: 230,
        awarenessGain: 0.44,
        losGain: 0.38,
        sprintGain: 0.9,
        illuminationGain: 1.85,
        awarenessThreshold: 0.5,
        detectionTime: 0.68,
        alertTime: 0.2,
        chaseSpeed: 132,
        huntSpeed: 94,
        searchTime: 4.2,
        lostTime: 2.4,
        searchRadius: 58,
        attackRange: 20,
        stationary: false,
      },
      WATCHER: {
        radius: 15,
        proximityRange: 82,
        losRange: 260,
        sprintRange: 210,
        awarenessGain: 0.62,
        losGain: 0.86,
        sprintGain: 0.4,
        illuminationGain: 2.4,
        awarenessThreshold: 0.32,
        detectionTime: 0.95,
        alertTime: 0.85,
        chaseSpeed: 52,
        huntSpeed: 36,
        searchTime: 7,
        lostTime: 5,
        searchRadius: 42,
        attackRange: 18,
        stationary: true,
      },
    },
  },

  audio: {
    masterVolume: 0.8,
    sfxVolume: 0.9,
    ambienceVolume: 0.72,
    stingCooldown: 4.2,
    heartbeatSilentBelow: 0,
    mix: {
      ambienceBed: 0.72,
      menuMusic: 0.68,
      threatMusicMax: 0.82,
      threatMusicCurve: [
        [0.0, 0.0],
        [0.05, 0.03],
        [0.1, 0.06],
        [0.2, 0.14],
        [0.4, 0.32],
        [0.6, 0.52],
        [0.8, 0.72],
        [1.0, 0.88],
      ],
      heartbeatBus: 1.42,
      heartbeatPulseGain: 1.38,
      heartbeatBaseline: 0.58,
      heartbeatLow: 0.32,
      heartbeatMedium: 0.55,
      heartbeatHigh: 0.76,
      heartbeatCritical: 1.08,
      playerWalkStep: 0.62,
      playerRunStep: 0.78,
      playerStepBus: 0.96,
      enemySafe: 0.82,
      enemyCritical: 1.0,
      enemyStepMul: 0.68,
      pickupVolume: 0.88,
      doorVolume: 0.85,
      gameOverVolume: 0.92,
      sfxBus: 1.0,
    },
    heartbeatBpm: [
      [0.0, 50],
      [0.25, 62],
      [0.5, 82],
      [0.75, 112],
      [1.0, 148],
    ],
  },

  threat: {
    maxDistance: 640,
    nearDistance: 24,
    riseRate: 2.8,
    fallRate: 0.65,
    sprintBonus: 0.05,
    secondaryEnemyScale: 0.34,
    illuminatedBonus: 0.1,
    occludedScale: 0.68,
    stateWeights: {
      DORMANT: 0.5,
      AWARE: 0.58,
      ILLUMINATED: 0.64,
      ALERT: 0.74,
      HUNTING: 1,
      SEARCHING: 0.6,
      LOST: 0.3,
    },
  },

  effects: {
    screenShake: true,
    visualEffects: true,
    grainIntensity: 0.035,
    vignetteIntensity: 0.4,
    cameraSmoothing: 10,
  },

  difficulty: {
    baseEnemyCount: 1,
    maxEnemyCount: 3,
    speedScalePerRoom: 0.04,
    batteryDrainScale: 0.015,
    earlyRoomBatteryMultiplier: 0.55,
    earlyRoomCount: 3,
  },

  timing: {
    maxDeltaTime: 0.05,
    introDelay: 1.5,
    deathDelay: 2.5,
    roomTransition: 1.8,
  },

  colors: {
    background: '#050607',
    wall: '#1B2026',
    wallInner: '#151A20',
    wallEdge: '#2A3038',
    wallHighlight: '#343A42',
    floor: '#11151A',
    floorAlt: '#0E1217',
    floorLine: '#1A2028',
    metal: '#343A42',
    object: '#252B32',
    objectHighlight: '#2F363F',
    shadow: '#000000',
    flashlight: '#FFF4D6',
    flashlightCore: '#FFFBE8',
    danger: '#C94B4B',
    emergency: '#C94B4B',
    ui: '#E6E6E6',
    uiSecondary: '#8B9199',
    enemy: '#060606',
    enemyEyes: '#B8A080',
    playerCoat: '#30363D',
    playerSecondary: '#20252A',
    playerSkin: '#4A4F55',
    objective: '#D9D2B0',
    exit: '#7FBF8A',
    exitGlow: '#5A9A64',
    decor: '#252B32',
    power: '#D9A441',
    lab: '#6A9FBF',
  },
};

export const TILE = {
  EMPTY: 0,
  WALL: 1,
  FLOOR: 2,
  EXIT: 3,
  OBJECTIVE: 4,
  DECOR: 5,
};

export const GAME_STATE = {
  BOOT: 'BOOT',
  MENU: 'MENU',
  INTRO: 'INTRO',
  PLAYING: 'PLAYING',
  PAUSED: 'PAUSED',
  DEAD: 'DEAD',
  TRANSITIONING: 'TRANSITIONING',
};

export const ENEMY_STATE = {
  DORMANT: 'DORMANT',
  AWARE: 'AWARE',
  ILLUMINATED: 'ILLUMINATED',
  ALERT: 'ALERT',
  HUNTING: 'HUNTING',
  SEARCHING: 'SEARCHING',
  LOST: 'LOST',
};

export const ENEMY_ARCHETYPE = {
  STALKER: 'STALKER',
  RUNNER: 'RUNNER',
  WATCHER: 'WATCHER',
};

export const OBJECTIVE_TYPE = {
  FIND_FUSE: 'FIND_FUSE',
  ACTIVATE_GENERATOR: 'ACTIVATE_GENERATOR',
  COLLECT_KEY: 'COLLECT_KEY',
  FIND_EXIT_CODE: 'FIND_EXIT_CODE',
};

export const OBJECTIVE_HINTS = {
  [OBJECTIVE_TYPE.FIND_FUSE]: 'Maintenance equipment may contain one.',
  [OBJECTIVE_TYPE.ACTIVATE_GENERATOR]: 'Look near the starting area.',
  [OBJECTIVE_TYPE.COLLECT_KEY]: 'Check desks and cabinets.',
  [OBJECTIVE_TYPE.FIND_EXIT_CODE]: 'Office terminals may have it.',
};
